#SPDX-License-Identifier: MIT-0
---
# tasks file for install_package

- name: "Installing Packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
  when: packages is defined
  become: true
  become_method: sudo
  tags:
    - install_package
