#SPDX-License-Identifier: MIT-0
---
# tasks file for chart_install

- name: Create a namespace
  kubernetes.core.k8s:
    state: present
    definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
        labels: "{{ namespace_labels }}"
        annotations: "{{ namespace_annotations }}"
  environment:
    KUBECONFIG: "/home/{{ansible_ssh_user}}/.kube/config"

# Checkout repo
- name: Remove git directory
  ansible.builtin.file:
    path: /tmp/helm_repo
    state: absent

- name: Git clone stable repo on HEAD
  ansible.builtin.git:
    repo: "{{ chart_repo }}"
    dest: /tmp/helm_repo

- name: Build helm dependencies
  ansible.builtin.command:
    cmd: "helm dependency build /tmp/helm_repo{{chart_loc}}"
  changed_when: true
  environment:
    KUBECONFIG: "/home/{{ansible_ssh_user}}/.kube/config"

- name: Deploy chart from local path
  kubernetes.core.helm:
    name: "{{ app_name }}"
    chart_ref: "/tmp/helm_repo{{ chart_loc }}"
    namespace: "{{ namespace }}"
  environment:
    KUBECONFIG: "/home/{{ansible_ssh_user}}/.kube/config"

- name: Remove git directory
  ansible.builtin.file:
    path: /tmp/helm_repo
    state: absent

- name: Wait for safety
  ansible.builtin.pause:
    minutes: "{{ post_install_delay }}"
