argument_specs:
  # roles/common/install_package/main.yml
  main:
    short_description: Installs a set of packages on the host
    description:
      - This role installs a list of packages on the host
      - It will automatically becomes the become_user useer for these actions.
    author:
      - BlindGarret
    options:
      packages:
        description:
          - The names of the packages to install
        required: true
        type: list
