# Ensure version of packages exist before attempting changes

# CRI-O & K8s

- name: Check CRI-O Repos Initial Existence
  ansible.builtin.stat:
    path: /etc/yum.repos.d/crio.repo
  register: crio_repo_initial_exists

- name: Check K8s Repos Initial Existence
  ansible.builtin.stat:
    path: /etc/yum.repos.d/k8s.repo
  register: k8s_repo_initial_exists


- name: Check Version Availability
  block:
    - name: Copy K8s Repo Definition
      ansible.builtin.copy:
        src: /etc/yum.repos.d/k8s.repo
        dest: /etc/yum.repos.d/k8s.repo.old
        remote_src: true
        force: true
        mode: '0644'
      when: k8s_repo_initial_exists.stat.exists == true

    - name: Copy CRI-O Repo Definition
      ansible.builtin.copy:
        src: /etc/yum.repos.d/crio.repo
        dest: /etc/yum.repos.d/crio.repo.old
        remote_src: true
        force: true
        mode: '0644'
      when: crio_repo_initial_exists.stat.exists == true
    
    - name: Remove copied CRI-O repo files
      ansible.builtin.file:
        path: /etc/yum.repos.d/crio.repo
        state: absent

    - name: Remove copied K8s repo files
      ansible.builtin.file:
        path: /etc/yum.repos.d/k8s.repo
        state: absent

    - name: Replace CRI-O repo definition
      ansible.builtin.copy:
        dest: '/etc/yum.repos.d/crio.repo'
        content: |
          [cri-o]
          name=CRI-O
          baseurl=https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v{{crio_version}}/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v{{crio_version}}/rpm/repodata/repomd.xml.key
        mode: '0644'
        force: true
        follow: yes

    - name: Replace K8s-O repo definition
      ansible.builtin.copy:
        dest: '/etc/yum.repos.d/k8s.repo'
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v{{k8s_version}}/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v{{k8s_version}}/rpm/repodata/repomd.xml.key
        mode: '0644'
        force: true
        follow: yes

    - name: Lookup CRI-O Version
      ansible.builtin.shell: |
        dnf search --showduplicates cri-o | grep {{crio_version}}
      register: crio_version_found

    - name: Lookup K8s Version
      ansible.builtin.shell: |
        dnf search --showduplicates kubeadm | grep {{k8s_version}}
      register: k8s_version_found

    - name: Check if K8s version exists
      ansible.builtin.fail:
        msg: "Kubernetes version {{k8s_version}} not found in repo"
      when: k8s_version_found.rc != 0

    - name: Check if CRI-O version exists
      ansible.builtin.fail:
        msg: "CRI-O version {{k8s_version}} not found in repo"
      when: crio_version_found.rc != 0

  always:
    - name: Revert CRI-O Repo Definition
      ansible.builtin.copy:
        src: /etc/yum.repos.d/crio.repo.old
        dest: /etc/yum.repos.d/crio.repo
        remote_src: true
        force: true
        mode: '0644'
      when: crio_repo_initial_exists.stat.exists == true

    - name: Revert K8s Repo Definition
      ansible.builtin.copy:
        src: /etc/yum.repos.d/k8s.repo.old
        dest: /etc/yum.repos.d/k8s.repo
        remote_src: true
        force: true
        mode: '0644'
      when: k8s_repo_initial_exists.stat.exists == true

    - name: Cleanup additional CRI-O repo files
      ansible.builtin.file:
        path: /etc/yum.repos.d/crio.repo
        state: absent
      when: crio_repo_initial_exists.stat.exists == false

    - name: Cleanup additional K8s repo files
      ansible.builtin.file:
        path: /etc/yum.repos.d/k8s.repo
        state: absent
      when: k8s_repo_initial_exists.stat.exists == false

    - name: Remove Copy of CRI-O Repo Definition
      ansible.builtin.file:
        path: /etc/yum.repos.d/crio.repo.old
        state: absent
    - name: Remove Copy of k8s Repo Definition
      ansible.builtin.file:
        path: /etc/yum.repos.d/k8s.repo.old
        state: absent
