- hosts: all
  roles:
    - role: ../../roles/common/create-user
      username: "{{ jb_username }}"
      ssh_key_name: "{{ jb_ssh_key_name }}" 
      is_sudoer: true
      skip_sudoer_password: true
