argument_specs:
  main:
    short_description: Installs a Helm Chart
    description:
      - Installs a helmchart to the kubernetes cluster
    author:
      - BlindGarret
    options:
      chart_repo:
        description:
          - The repository to find the helm chart
        required: true
        type: str
      chart_loc:
        description:
          - The location of the helm chart in the repo
          - this path should be absolute, treating the root as the repos root with a leading /
          - for example if the chart was in file foo in file bar the path would be /bar/foo
        required: false
        default: ""
        type: str
      app_name:
        description:
          - The name of the application to install
        required: true
        type: str
      namespace:
        description:
          - The namespace to install the application in
        required: true
        type: str
      post_install_delay:
        description:
          - The delay to wait after the installation in minutes
          - This allows for safety delays as systems start up
        required: false
        default: 0
        type: int
      namspace_labels:
        description:
          - The labels to add to the namespace
          - This is a dictionary of key value pairs
        required: false
        default: {}
        type: complex
      namespace_annotations:
        description:
          - The annotations to add to the namespace
          - This is a dictionary of key value pairs
        required: false
        type: complex
