argument_specs:
  main:
    short_description: Creates a CA for the cluster
    description:
      - Create a self signed CA for the cluster
      - If the given secret already exists it just loads the cert into memory for other roles to use
    author:
      - BlindGarret
    options:
      ca_c:
        required: false
        type: str
      ca_st:
        required: false
        type: str
      ca_l:
        required: false
        type: str
      ca_o:
        required: true
        type: str
      ca_ou:
        required: true
        type: str
      ca_cn:
        required: true
        type: str
      secret_name:
        description:
          - The name of the secret to create
        required: true
        type: str
      secret_namespace:
        description:
          - The namespace to create the secret in
        required: true
        type: str
