argument_specs:
  main:
    short_description: Adds a cert to the host as a trusted cert.
    description:
      - Adds the cert loaded into memory as a trusted cert to the host.
    author:
      - BlindGarret
    options:
      cert_name:
        description:
          - The name of the cert to add
        required: true
        type: str
