---
- name: Ensure nfs-backup-provisioner namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ nfs_backup_provisioner_kubeconfig }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ nfs_backup_provisioner_namespace }}"

- name: Render NFS backup provisioner values
  template:
    src: values.yaml.j2
    dest: /tmp/nfs-backup-provisioner-values.yaml
    mode: "0644"

- name: Install/upgrade nfs-backup-subdir-external-provisioner chart
  kubernetes.core.helm:
    name: "{{ nfs_backup_provisioner_release_name }}"
    chart_ref: "{{ nfs_backup_provisioner_chart_name }}"
    chart_repo_url: "{{ nfs_backup_provisioner_chart_repo }}"
    chart_version: "{{ nfs_provisioner_chart_version }}"
    namespace: "{{ nfs_backup_provisioner_namespace }}"
    values_files:
      - /tmp/nfs-backup-provisioner-values.yaml
    kubeconfig: "{{ nfs_backup_provisioner_kubeconfig }}"
    wait: true
