argument_specs:
  main:
    short_description: Installs Calico
    description:
      - Install Calico to the contoller
    author:
      - BlindGarret
    options:
      calico_chart_version:
        description:
          - The version of the helm chart for calico to install
        required: true
        type: str
